
import {Accessibility as AccessibleIcon, ArrowRight, Check, ChevronsUpDown, Circle, Copy, Edit, ExternalLink, File, HelpCircle, Home, Loader2, Mail, MessageSquare, Moon, Package, CircleParkingIcon as ParkingIcon, Phone, Plus, PlusCircle, Bath, Search, Armchair, Server, Settings, Share2, Shield, Sun, Trash, Truck, User, Utensils, X, Workflow, Hotel, Baby, Sofa} from 'lucide-react';
import { Beer, Milk, Carrot, Martini, Coffee, CreditCard, IdCard, Menu, Heart, Zap, Map, Moon as MoonIcon, Nfc, Pizza, Smile, Sun as SunIcon, Trophy, Users as UsersIcon, Wine } from 'lucide-react';

const Icons = {
  arrowRight: ArrowRight,
  check: Check,
  chevronDown: ChevronsUpDown,
  circle: Circle,
  workflow: Workflow,
  close: X,
  copy: Copy,
  dark: Moon,
  edit: Edit,
  externalLink: ExternalLink,
  file: File,
  help: HelpCircle,
  home: Home,
  light: Sun,
  loader: Loader2,
  mail: Mail,
  messageSquare: MessageSquare,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  spinner: Loader2,
  trash: Trash,
  user: User,
  accessible: AccessibleIcon,
  truck: Truck,
  package: Package,
  utensils: Utensils,
  lightning: Zap,
  beer: Beer,
  cocktail: Martini,
  trophy: Trophy,
  sun: SunIcon,
  moon: MoonIcon,
  users: UsersIcon,
  heart: Heart,
  wine: Wine,
  coffee: Coffee,
  pizza: Pizza,
  hamburger: Menu,
  smile: Smile,
  bottle: Milk,
  carrot: Carrot,
  creditCard: CreditCard,
  debitCard: IdCard,
  nfc: Nfc,
  baby: Baby,
  chair: Sofa,
  parking: ParkingIcon,
  seating: Armchair,
  restroom: Bath,
  bar: Hotel,
  map: Map,
  phone: Phone
};

export {Icons};

    